---
title: "Test de R Markdown"
author: "FIRSTNAME FAMILYNAME"
date: 2018-09-24T18:36:00-01:00
categories: ["R"]
tags: ["R Markdown", "website"]
draft: false
summary: "Quelques exemples de formattages R Markdown"
---

Dans un document R Markdown on peut utiliser naturellement la syntaxe Markdown, mais aussi du code R dans des "chunks", comme ci-dessous pour générer un graphique (Fig. \@ref(fig:pie)) :

```{r pie, fig.cap='Un superbe graphique en camembert.', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Sky', 'Sunny side of pyramid', 'Shady side of pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

{{% alert note %}}
Une section `alert note` mets un paragraphe en évidence.
{{% /alert %}}


## Hugo shortcodes

Tweet

```{r echo=FALSE}
blogdown::shortcode('tweet', '936232450006704128')
```

Youtube

```{r echo=FALSE}
blogdown::shortcode('youtube', 'ZwYQPtU2Pa0') # or 'w7Ft2ymGmfc'
```

Vimeo

```{r echo=FALSE}
blogdown::shortcode('vimeo', '146022717')
```

Github Gist

```{r echo=FALSE}
blogdown::shortcode('gist', 'phgrosjean', 'f1d53c0dc1124522b2138033188497d0')
```

Speakerdeck

```{r echo=FALSE}
blogdown::shortcode('speakerdeck', '4e8126e72d853c0060001f97')
```

Figure

```{r echo=FALSE}
blogdown::shortcode('figure', src = '/img/project.jpg', alt = "Une belle grenouille")
```

